<?php

<<<<<<< HEAD:var/cache/dev/ContainerPsj1wGM/get_ServiceLocator__Ewpm5QService.php
namespace ContainerPsj1wGM;
=======
namespace ContainerGsjgqAv;

>>>>>>> 46ca464b0d52b612cb2c8c978a05b404bff82702:var/cache/dev/ContainerGsjgqAv/get_ServiceLocator__Ewpm5QService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Ewpm5QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ewpm5Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..ewpm5Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'professeur' => ['privates', '.errored..service_locator..ewpm5Q.App\\Entity\\Professeur', NULL, 'Cannot autowire service ".service_locator..ewpm5Q": it references class "App\\Entity\\Professeur" but no such service exists.'],
        ], [
            'professeur' => 'App\\Entity\\Professeur',
        ]);
    }
}
