<?php

<<<<<<< HEAD:var/cache/dev/ContainerJCBBj76/getClasseService.php
namespace ContainerJCBBj76;
=======
namespace ContainerGsjgqAv;

>>>>>>> 46ca464b0d52b612cb2c8c978a05b404bff82702:var/cache/dev/ContainerGsjgqAv/getClasseService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClasseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.88DCWcy.App\Entity\Classe' shared service.
     *
     * @return \App\Entity\Classe
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.88DCWcy": it references class "App\\Entity\\Classe" but no such service exists.');
    }
}
