<?php

<<<<<<< HEAD:var/cache/dev/ContainerJCBBj76/getProfesseurService.php
namespace ContainerJCBBj76;
=======
namespace ContainerGsjgqAv;

>>>>>>> 46ca464b0d52b612cb2c8c978a05b404bff82702:var/cache/dev/ContainerGsjgqAv/getProfesseurService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..ewpm5Q.App\Entity\Professeur' shared service.
     *
     * @return \App\Entity\Professeur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..ewpm5Q": it references class "App\\Entity\\Professeur" but no such service exists.');
    }
}
