<?php

<<<<<<< HEAD:var/cache/dev/ContainerJCBBj76/getSearchDtoService.php
namespace ContainerJCBBj76;
=======
namespace ContainerGsjgqAv;

>>>>>>> 46ca464b0d52b612cb2c8c978a05b404bff82702:var/cache/dev/ContainerGsjgqAv/getSearchDtoService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rAlqQ78.EasyCorp\Bundle\EasyAdminBundle\Dto\SearchDto' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Dto\SearchDto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rAlqQ78": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Dto\\SearchDto" but no such service exists.');
    }
}
