<?php

namespace ContainerBmxpa2T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B3GXs3XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B3GXs3X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B3GXs3X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', true],
        ], [
            'em' => '?',
            'validator' => '?',
        ]);
    }
}
