<?php

namespace ContainerWhPs6SQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G0GYwWTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g0GYwWT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g0GYwWT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mr' => ['privates', 'App\\Repository\\MatiereRepository', 'getMatiereRepositoryService', true],
            'pr' => ['privates', 'App\\Repository\\ProfesseurRepository', 'getProfesseurRepositoryService', true],
            'sr' => ['privates', '.errored.e9tNKkf', NULL, 'Cannot determine controller argument for "App\\Controller\\Api\\CoursController::createCours()": the $sr argument is type-hinted with the non-existent class or interface: "SalleRepository".'],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', true],
        ], [
            'em' => '?',
            'mr' => 'App\\Repository\\MatiereRepository',
            'pr' => 'App\\Repository\\ProfesseurRepository',
            'sr' => '?',
            'validator' => '?',
        ]);
    }
}
