<?php

namespace ContainerEgJVXAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JYCLLoWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JYCLLoW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JYCLLoW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ProfesseurRepository', 'getProfesseurRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ProfesseurRepository',
        ]);
    }
}
