<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJeTqwwK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJeTqwwK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJeTqwwK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJeTqwwK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJeTqwwK\App_KernelDevDebugContainer([
    'container.build_hash' => 'JeTqwwK',
    'container.build_id' => '06699014',
    'container.build_time' => 1615540841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJeTqwwK');
