<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRkkc1vv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRkkc1vv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRkkc1vv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRkkc1vv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRkkc1vv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rkkc1vv',
    'container.build_id' => 'c98dc370',
    'container.build_time' => 1615288103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRkkc1vv');
