<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHgWadE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHgWadE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHgWadE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHgWadE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHgWadE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHgWadE',
    'container.build_id' => 'e21f7d94',
    'container.build_time' => 1615475580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHgWadE');
