<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'api_professeurs_index' => [[], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::index'], [], [['text', '/api/professeurs']], [], []],
    'api_professeurs_show' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_professeurs_index_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::indexAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_professeurs_create_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::createAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], []],
    'api_professeurs_delete_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::deleteAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs/avis']], [], []],
    'api_professeurs_update_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::updateAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs/avis']], [], []],
    'professeurs_index' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::index'], [], [['text', '/professeurs']], [], []],
    'professeurs_create' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::create'], [], [['text', '/professeurs/create']], [], []],
    'professeurs_update' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs/update']], [], []],
    'professeurs_delete' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs/delete']], [], []],
];
